apiVersion: catalog.kubedb.com/v1alpha1
kind: MongoDBVersion
metadata:
  annotations:
    meta.helm.sh/release-name: kubedb-catalog
    meta.helm.sh/release-namespace: kubedb
  labels:
    app.kubernetes.io/instance: kubedb-catalog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubedb-catalog
    app.kubernetes.io/version: v2024.1.7-beta.0
    helm.sh/chart: kubedb-catalog-v2024.1.7-beta.0
  name: percona-6.0.12-4
spec:
  archiver:
    addon:
      name: mongodb-addon
      tasks:
        manifestBackup:
          name: ManifestBackup
        manifestRestore:
          name: ManifestRestore
        volumeSnapshot:
          name: VolumeSnapshot
    walg:
      image: ghcr.io/kubedb/wal-g:v2023.11.30_mongo
  db:
    image: percona/percona-server-mongodb:6.0.12
  distribution: Percona
  exporter:
    image: ghcr.io/kubedb/mongodb_exporter:v0.32.0
  gitSyncer:
    image: registry.k8s.io/git-sync/git-sync:v4.1.0
  initContainer:
    image: ghcr.io/kubedb/mongodb-init:4.2-v9
  podSecurityPolicies:
    databasePolicyName: mongodb-db
  replicationModeDetector:
    image: ghcr.io/kubedb/replication-mode-detector:v0.28.0-beta.0
  securityContext:
    runAsUser: 999
  stash:
    addon:
      backupTask:
        name: mongodb-backup-4.4.6
      restoreTask:
        name: mongodb-restore-4.4.6
  updateConstraints:
    allowlist:
    - '>= 5.0.0'
  version: 6.0.12
