apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: pp
  namespace: demo
spec:
  allowedSchemas:
    namespaces:
      from: Selector
      selector:
        matchExpressions:
        - {key: kubernetes.io/metadata.name, operator: In, values: [dev]}
    selector:
      matchLabels:
        "schema.kubedb.com": "mongo"
  terminationPolicy: WipeOut
  # version: percona-4.4.10
  # version: percona-5.0.23 
  # version: percona-6.0.11
  version: percona-5.0.23
  replicaSet:
    name: "replicaset"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: "600m"
          memory: "600Mi"
  replicas: 1
  # storageEngine: inMemory
  # storageType: Ephemeral
  # ephemeralStorage:
  #   sizeLimit: "900Mi"
  storage:
    # storageClassName: longhorn
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  # sslMode: requireSSL
  # tls:
  #   issuerRef:
  #     apiGroup: "cert-manager.io"
  #     kind: Issuer
  #     name: mongo-ca-issuer
  # clusterAuthMode: x509