apiVersion: meta.k8s.appscode.com/v1alpha1
kind: ResourceCalculator
request:
  resource:
    apiVersion: kubedb.com/v1alpha2
    kind: MongoDB
    metadata:
      annotations:
        kubectl.kubernetes.io/last-applied-configuration: |
          {"apiVersion":"kubedb.com/v1alpha2","kind":"MongoDB","metadata":{"annotations":{},"name":"repl6","namespace":"demo"},"spec":{"arbiter":{"podTemplate":{}},"replicaSet":{"name":"rs1"},"replicas":2,"storage":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"10Gi"}}},"terminationPolicy":"WipeOut","version":"6.0.12"}}
      creationTimestamp: "2024-05-24T13:53:45Z"
      finalizers:
      - kubedb.com
      generation: 3
      name: repl6
      namespace: demo
      resourceVersion: "224197"
      uid: f8ddde4d-9952-4d42-9d4c-16eb997831a1
    spec:
      allowedSchemas:
        namespaces:
          from: Same
      arbiter:
        podTemplate:
          controller: {}
          metadata: {}
          spec:
            affinity:
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/instance: repl6
                        app.kubernetes.io/managed-by: kubedb.com
                        app.kubernetes.io/name: mongodbs.kubedb.com
                    namespaces:
                    - demo
                    topologyKey: kubernetes.io/hostname
                  weight: 100
                - podAffinityTerm:
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/instance: repl6
                        app.kubernetes.io/managed-by: kubedb.com
                        app.kubernetes.io/name: mongodbs.kubedb.com
                    namespaces:
                    - demo
                    topologyKey: failure-domain.beta.kubernetes.io/zone
                  weight: 50
            containerSecurityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                - ALL
              runAsGroup: 999
              runAsNonRoot: true
              runAsUser: 999
              seccompProfile:
                type: RuntimeDefault
            livenessProbe:
              exec:
                command:
                - bash
                - -c
                - "set -x; if [[ $(mongosh admin --host=localhost   --quiet --eval \"db.adminCommand('ping').ok\"
                  ) -eq \"1\" ]]; then \n          exit 0\n        fi\n        exit 1"
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            readinessProbe:
              exec:
                command:
                - bash
                - -c
                - "set -x; if [[ $(mongosh admin --host=localhost   --quiet --eval \"db.adminCommand('ping').ok\"
                  ) -eq \"1\" ]]; then \n          exit 0\n        fi\n        exit 1"
              failureThreshold: 3
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 5
            resources:
              limits:
                memory: 1Gi
              requests:
                cpu: 800m
                memory: 1Gi
            securityContext:
              fsGroup: 999
      authSecret:
        name: repl6-auth
      autoOps: {}
      clusterAuthMode: keyFile
      coordinator:
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 999
          runAsNonRoot: true
          runAsUser: 999
          seccompProfile:
            type: RuntimeDefault
      healthChecker:
        failureThreshold: 1
        periodSeconds: 10
        timeoutSeconds: 10
      keyFileSecret:
        name: repl6-key
      podTemplate:
        controller: {}
        metadata: {}
        spec:
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: repl6
                      app.kubernetes.io/managed-by: kubedb.com
                      app.kubernetes.io/name: mongodbs.kubedb.com
                  namespaces:
                  - demo
                  topologyKey: kubernetes.io/hostname
                weight: 100
              - podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app.kubernetes.io/instance: repl6
                      app.kubernetes.io/managed-by: kubedb.com
                      app.kubernetes.io/name: mongodbs.kubedb.com
                  namespaces:
                  - demo
                  topologyKey: failure-domain.beta.kubernetes.io/zone
                weight: 50
          containerSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            runAsGroup: 999
            runAsNonRoot: true
            runAsUser: 999
            seccompProfile:
              type: RuntimeDefault
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - "set -x; if [[ $(mongosh admin --host=localhost  --username=$MONGO_INITDB_ROOT_USERNAME
                --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
                --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
                \         exit 0\n        fi\n        exit 1"
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - bash
              - -c
              - "set -x; if [[ $(mongosh admin --host=localhost  --username=$MONGO_INITDB_ROOT_USERNAME
                --password=$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase=admin
                --quiet --eval \"db.adminCommand('ping').ok\" ) -eq \"1\" ]]; then \n
                \         exit 0\n        fi\n        exit 1"
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 800m
              memory: 1Gi
          securityContext:
            fsGroup: 999
          serviceAccountName: repl6
      replicaSet:
        name: rs1
      replicas: 2
      sslMode: disabled
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
      storageEngine: wiredTiger
      storageType: Durable
      terminationPolicy: WipeOut
      version: 6.0.12
    status:
      conditions:
      - lastTransitionTime: "2024-05-24T13:53:45Z"
        message: 'The KubeDB operator has started the provisioning of MongoDB: demo/repl6'
        reason: DatabaseProvisioningStartedSuccessfully
        status: "True"
        type: ProvisioningStarted
      - lastTransitionTime: "2024-05-28T11:44:39Z"
        message: 'The MongoDB: demo/repl6 secondary is synced.'
        observedGeneration: 3
        status: "True"
        type: ReplicaReady
      - lastTransitionTime: "2024-05-24T14:53:45Z"
        message: 'The MongoDB: demo/repl6 is accepting client requests.'
        observedGeneration: 3
        reason: DatabaseAcceptingConnectionRequest
        status: "True"
        type: AcceptingConnection
      - lastTransitionTime: "2024-05-24T14:53:45Z"
        message: 'The MongoDB: demo/repl6 is ready.'
        observedGeneration: 3
        reason: ReadinessCheckSucceeded
        status: "True"
        type: Ready
      - lastTransitionTime: "2024-05-24T14:53:58Z"
        message: 'The MongoDB: demo/repl6 is successfully provisioned.'
        observedGeneration: 3
        reason: DatabaseSuccessfullyProvisioned
        status: "True"
        type: Provisioned
      observedGeneration: 3
      phase: Ready