apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: ha
  namespace: demo
spec:
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
  storageType: Durable
  terminationPolicy: Delete
  version: "15.5"