# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: test-pv
# spec:
#   accessModes:
#   - ReadWriteOnce
#   capacity:
#     storage: 5Gi
#   hostPath:
#     path: /some-random-dir
#     type: ""
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: linode-block-storage-retain
#   volumeMode: Filesystem

---



---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: linode-block-storage-retain
  volumeMode: Filesystem
  # volumeName: test-pv