apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: compute
  namespace: demo
spec:
  databaseRef:
    name: simple
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    replicaSet:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 30
      minAllowed:
        cpu: 868m
        memory: 2.65Gi
      maxAllowed:
        cpu: 15890m
        memory: 57.27Gi
      controlledResources: ["cpu", "memory"]
      containerControlledValues: "RequestsAndLimits"
    nodeTopology:
      name: gke-pools

