apiVersion: kubedb.com/v1alpha2
kind: MongoDB
metadata:
  name: simple
  namespace: demo
spec:
  version: "4.4.26"
  terminationPolicy: WipeOut
  replicas: 3
  replicaSet:
    name: "rs"
  podTemplate:
    spec:
      nodeSelector:
        database: "yes"
      tolerations:
      - key: nodepool
        value: std2
        effect: NoSchedule
      resources:
        requests:
          "cpu": 965m
          "memory": 2.95Gi
        limits:
          "cpu": 1930
          "memory": 5.89Gi
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  # arbiter: 
  #   podTemplate:
  #     spec:
  #       # nodeSelector:
  #       #   cloud.google.com/gke-nodepool: medium
  #       tolerations:
  #       - key: nodepool
  #         value: medium
  #         effect: NoSchedule
  #       resources:
  #         requests:
  #           "cpu": 0.4
  #           "memory": 400Mi
  # monitor:
  # #   agent: prometheus.io/builtin
  #   agent: prometheus.io/operator
  #   prometheus:
  #     serviceMonitor:
  #       labels:
  #         release: prometheus
  #     exporter:
  #       args: ["--compatible-mode"]





nodeSelector:
  app: kubedb
  instance: mongodb
  component: mg-database
  nodepool_type: tiny
tolerations:
  - effect: NoSchedule
    key: app
    operator: Equal
    value: kubedb
  - effect: NoSchedule
    key: instance
    operator: Equal
    value: mongodb
  - effect: NoSchedule
    key: component
    operator: Equal
    value: mg-database
  - effect: NoSchedule
    key: nodepool_type
    operator: Equal
    value: tiny


app.kubernetes.io/component=database,
app.kubernetes.io/instance=large,
app.kubernetes.io/managed-by=kubedb.com,
app.kubernetes.io/name=mongodbs.kubedb.com