apiVersion: node.k8s.appscode.com/v1alpha1
kind: NodeTopology
metadata:
  name: lke-pools
spec:
  nodeSelectionPolicy: LabelSelector
  topologyKey: "node.kubernetes.io/instance-type"
  nodeGroups: # capacities here are actually slightly less than the allocatable resources.
  - topologyValue: g6-standard-1
    allocatable:
      cpu: "1"
      memory: 2021654528456m # 1928Mi
  - topologyValue: g6-standard-2
    allocatable:
      cpu: "2"
      memory: 4103083008321m # 3913Mi
  - topologyValue: g6-standard-4
    allocatable:
      cpu: "4"
      memory: 8Gi
  - topologyValue: g6-standard-6
    allocatable:
      cpu: "6"
      memory: 16Gi


# 1500m
# 3.11Gi

# I1226 07:30:07.503010       1 nodepool.go:159] Recommended NodeGroup is 1 Calculated new NodeGroup index is 2 
# I1226 07:30:07.503016       1 nodepool.go:107] MidPoints :: 
# I1226 07:30:07.503023       1 nodepool.go:127] 0 map[cpu:{i:{value:500 scale:-3} d:{Dec:<nil>} s:500m Format:DecimalSI} memory:{i:{value:1020054732800 scale:-3} d:{Dec:<nil>} s:1020054732800m Format:DecimalSI}] 
# I1226 07:30:07.503047       1 nodepool.go:127] 1 map[cpu:{i:{value:1500 scale:-3} d:{Dec:<nil>} s:1500m Format:DecimalSI} memory:{i:{value:3113851289600 scale:-3} d:{Dec:<nil>} s:3113851289600m Format:DecimalSI}] 
# I1226 07:30:07.503057       1 nodepool.go:127] 2 map[cpu:{i:{value:3000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:6388763852800 scale:-3} d:{Dec:<nil>} s:6388763852800m Format:DecimalSI}] 
# I1226 07:30:07.503065       1 nodepool.go:127] 3 map[cpu:{i:{value:5000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI} memory:{i:{value:12884901888000 scale:-3} d:{Dec:<nil>} s: Format:DecimalSI}] 


# g6-standard-1
#     allocatable:
#       cpu: "1"
#       ephemeral-storage: "47484676837"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 1930764Ki
#       pods: "110"
#     capacity:
#       cpu: "1"
#       ephemeral-storage: 51524172Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 2033164Ki
#       pods: "110"
# g6-standard-2
#     allocatable:
#       cpu: "2"
#       ephemeral-storage: "76019768399"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 3925900Ki
#       pods: "110"
#     capacity:
#       cpu: "2"
#       ephemeral-storage: 82486728Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 4028300Ki
#       pods: "110"
# g6-standard-4
#     allocatable:
#       cpu: "4"
#       ephemeral-storage: "152115318123"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 8048008Ki
#       pods: "110"
#     capacity:
#       cpu: "4"
#       ephemeral-storage: 165055684Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 8150408Ki
#       pods: "110"
# g6-standard-6
#     allocatable:
#       cpu: "6"
#       ephemeral-storage: "304306417570"
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 16292760Ki
#       pods: "110"
#     capacity:
#       cpu: "6"
#       ephemeral-storage: 330193596Ki
#       hugepages-1Gi: "0"
#       hugepages-2Mi: "0"
#       memory: 16395160Ki
#       pods: "110"
