apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: count
  name: count
  namespace: demo
spec:
  containers:
  - env:
    - name: MONGODB_NAME
      value: mg-rs
    - name: MONGODB_NAMESPACE
      value: demo
    image: arnobkumarsaha/object-count
    imagePullPolicy: Always
    name: count
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default
  namespace: demo
rules:
- apiGroups: ["kubedb.com"]
  resources: ["mongodbs"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default
  namespace: demo
subjects:
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: default
  apiGroup: rbac.authorization.k8s.io