apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: as
  namespace: demo
spec:
  databaseRef:
    name: test
  opsRequestOptions:
    timeout: 10m
    apply: IfReady
  compute:
    standalone:
      trigger: "On"
      podLifeTimeThreshold: 10m
      resourceDiffPercentage: 20
      minAllowed:
        cpu: 400m
        memory: 400Mi
      maxAllowed:
        cpu: 1
        memory: 2Gi
      # controlledResources: ["cpu", "memory"]
      # containerControlledValues: "RequestsAndLimits"
    # nodeTopologyRef:
    #   name: gke-pools



# //func isCRDAvailable(kbClient client.Client, crdName string) bool {
# //	crdName += "." + autoscalingapi.GroupName
# //	var crd crdapi.CustomResourceDefinition
# //	err := kbClient.Get(context.TODO(), types.NamespacedName{
# //		Name: crdName,
# //	}, &crd)
# //	if err != nil && !kerr.IsNotFound(err) { // serious error
# //		klog.Errorf("error occurred while checking CRD availability = %v\n", err)
# //	}
# //	return err == nil
# //}