# cat mongod.conf
# net:
#    maxIncomingConnections: 20000
# kubectl create secret generic -n demo new-custom-config --from-file=./mongod.conf 

apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: reconfigure
  namespace: demo
spec:
  type: Reconfigure
  databaseRef:
    name: repl4
  # configuration:
  #   replicaSet:
  #     configSecret:
  #       name: new-custom-config
  configuration:
    replicaSet:
      applyConfig:
        mongod.conf: |-
          net:
            maxIncomingConnections: 30000
  timeout: 5m
  apply: IfReady
# status:
#   conditions:
#   - lastTransitionTime: "2024-06-03T09:52:02Z"
#     message: MongoDB ops request is reconfiguring database
#     observedGeneration: 1
#     reason: Reconfigure
#     status: "True"
#     type: Reconfigure
#   - lastTransitionTime: "2024-06-03T09:52:10Z"
#     message: check is master; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: CheckIsMaster--repl4-1
#   - lastTransitionTime: "2024-06-03T09:52:10Z"
#     message: evict pod; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: EvictPod--repl4-1
#   - lastTransitionTime: "2024-06-03T09:52:30Z"
#     message: check pod ready; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: CheckPodReady--repl4-1
#   - lastTransitionTime: "2024-06-03T09:52:30Z"
#     message: check is master; ConditionStatus:True; PodName:repl4-2
#     observedGeneration: 1
#     status: "True"
#     type: CheckIsMaster--repl4-2
#   - lastTransitionTime: "2024-06-03T09:52:30Z"
#     message: evict pod; ConditionStatus:True; PodName:repl4-2
#     observedGeneration: 1
#     status: "True"
#     type: EvictPod--repl4-2
#   - lastTransitionTime: "2024-06-03T09:52:50Z"
#     message: check pod ready; ConditionStatus:True; PodName:repl4-2
#     observedGeneration: 1
#     status: "True"
#     type: CheckPodReady--repl4-2
#   - lastTransitionTime: "2024-06-03T09:52:50Z"
#     message: check is master; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: CheckIsMaster--repl4-0
#   - lastTransitionTime: "2024-06-03T09:52:50Z"
#     message: step down; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: StepDown--repl4-0
#   - lastTransitionTime: "2024-06-03T09:52:50Z"
#     message: evict pod; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: EvictPod--repl4-0
#   - lastTransitionTime: "2024-06-03T09:53:10Z"
#     message: check pod ready; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: CheckPodReady--repl4-0
#   - lastTransitionTime: "2024-06-03T09:53:10Z"
#     message: Successfully Reconfigured MongoDB
#     observedGeneration: 1
#     reason: ReconfigureReplicaset
#     status: "True"
#     type: ReconfigureReplicaset
#   - lastTransitionTime: "2024-06-03T09:53:10Z"
#     observedGeneration: 1
#     status: "True"
#     type: ""
#   - lastTransitionTime: "2024-06-03T09:53:10Z"
#     message: Successfully completed the modification process.
#     observedGeneration: 1
#     reason: Successful
#     status: "True"
#     type: Successful
#   observedGeneration: 1
#   phase: Successful

