apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: rwo-as
  namespace: demo
spec:
  databaseRef:
    name: rwo
  storage:
    standalone:
      trigger: "On"
      expansionMode: "Online" / "Offline"
      usageThreshold: 60
      scalingRules:
      - appliesUpto: 500GB
        threshold: 30pc
      - appliesUpto: 1000GB
        threshold: 20pc
      - appliesUpto: ""
        threshold: 50GB
      scalingThreshold: 50
      upperBound: 2TB