apiVersion: autoscaling.kubedb.com/v1alpha1
kind: MongoDBAutoscaler
metadata:
  name: rwo-as
  namespace: demo
spec:
  databaseRef:
    name: rwo
  storage:
    standalone:
      trigger: "On"
      usageThreshold: 60
      scalingThreshold: 50