apiVersion: ops.kubedb.com/v1alpha1
kind: MongoDBOpsRequest
metadata:
  name: ver-600
  namespace: demo
spec:
  apply: Always
  databaseRef:
    name: repl4
  readinessCriteria:
    objectsCountDiffPercentage: 10
    oplogMaxLagSeconds: 20
  timeout: 5m
  type: VerticalScaling
  verticalScaling:
    replicaSet:
      resources:
        limits:
          cpu: "0.7"
          memory: 700Mi
        requests:
          cpu: "0.6"
          memory: 600Mi
# status:
#   conditions:
#   - lastTransitionTime: "2024-06-03T09:05:10Z"
#     message: MongoDB ops request is vertically scaling database
#     observedGeneration: 1
#     reason: VerticalScale
#     status: "True"
#     type: VerticalScale
#   - lastTransitionTime: "2024-06-03T09:05:18Z"
#     message: check is master; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: CheckIsMaster--repl4-0
#   - lastTransitionTime: "2024-06-03T09:05:18Z"
#     message: evict pod; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: EvictPod--repl4-0
#   - lastTransitionTime: "2024-06-03T09:05:33Z"
#     message: check pod ready; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: CheckPodReady--repl4-0
#   - lastTransitionTime: "2024-06-03T09:05:33Z"
#     message: check replicaset func; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: CheckReplicasetFunc--repl4-0
#   - lastTransitionTime: "2024-06-03T09:05:33Z"
#     message: object count; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: ObjectCount--repl4-0
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: oplog sync; ConditionStatus:True; PodName:repl4-0
#     observedGeneration: 1
#     status: "True"
#     type: OplogSync--repl4-0
#   - lastTransitionTime: "2024-06-03T09:05:33Z"
#     message: check is master; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: CheckIsMaster--repl4-1
#   - lastTransitionTime: "2024-06-03T09:05:43Z"
#     message: step down; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: StepDown--repl4-1
#   - lastTransitionTime: "2024-06-03T09:05:43Z"
#     message: evict pod; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: EvictPod--repl4-1
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: check pod ready; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: CheckPodReady--repl4-1
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: check replicaset func; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: CheckReplicasetFunc--repl4-1
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: object count; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: ObjectCount--repl4-1
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: oplog sync; ConditionStatus:True; PodName:repl4-1
#     observedGeneration: 1
#     status: "True"
#     type: OplogSync--repl4-1
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: Successfully Vertically Scaled Replicaset Resources
#     observedGeneration: 1
#     reason: VerticalScaleReplicaSet
#     status: "True"
#     type: VerticalScaleReplicaSet
#   - lastTransitionTime: "2024-06-03T09:06:15Z"
#     message: Successfully Vertically Scaled Database
#     observedGeneration: 1
#     reason: Successful
#     status: "True"
#     type: Successful
#   observedGeneration: 1
#   phase: Successful
