apiVersion: stash.appscode.com/v1beta1
kind: BackupConfiguration
metadata:
  name: mg-backup
  namespace: demo
spec:
  driver: Restic
  paused: true
  repository:
    name: gcs-repo
  retentionPolicy:
    keepLast: 5
    name: keep-last-5
    prune: true
  schedule: '*/5 * * * *'
  target:
    ref:
      apiVersion: appcatalog.appscode.com/v1alpha1
      kind: AppBinding
      name: mg
