apiVersion: schema.kubedb.com/v1alpha1
kind: MongoDBDatabase
metadata:
  name: mongodb-schema
  namespace: dev
  labels:
    "schema.kubedb.com": "mongo"
spec:
  database:
    serverRef:
      name: rsmg5
      namespace: demo
    config:
      name: emptydb
  vaultRef:
    name: vault
    namespace: vv
  accessPolicy:
    subjects:
      - name: "saname"
        namespace: dev
        kind: "ServiceAccount"
        apiGroup: ""
    defaultTTL: "10m"
    maxTTL: "200h"
  deletionPolicy: Delete