apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: pg1
  namespace: demo
spec:
  version: "15.5"
  replicas: 1
  storageType: Durable
  storage:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  podTemplate:
    spec:
      volumes:
        - name: init-secret
          secret:
            secretName: init-secret
      volumeMounts:
        - name: init-secret
          mountPath: /var/init/users/
  init:
    script:
      configMap:
        name: init-cm