apiVersion: kubedb.com/v1alpha2
kind: ZooKeeper
metadata:
  name: z83
  namespace: demo
spec:
  # version: "3.7.2"
  version: "3.8.3"
  version: "3.9.1"
  replicas: 3
  storage:
    resources:
      requests:
        storage: "2Gi"
    # storageClassName: "solr-storage"
    accessModes:
    - ReadWriteOnce
  terminationPolicy: Halt

  
